# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame_msg.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'frame_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66rame_msg.proto\x12\x08\x63m.proto\"\xd9\x01\n\x15ProcessingUnitContext\x12!\n\x19\x63\x61ptured_from_real_device\x18\x01 \x01(\x08\x12\x1c\n\x14\x63\x61pture_timestamp_ms\x18\x02 \x01(\x03\x12)\n!capture_from_this_device_since_ms\x18\x03 \x01(\x03\x12\x15\n\rframe_seq_num\x18\x04 \x01(\r\x12\x1b\n\x13processing_unit_idx\x18\x05 \x01(\x05\x12\x13\n\x0b\x63hange_rate\x18\x06 \x01(\x02\x12\x0b\n\x03\x66ps\x18\x07 \x01(\x02\"Z\n\x08\x46rameMsg\x12\x11\n\tis_cv_mat\x18\x01 \x01(\x08\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12,\n\x03\x63tx\x18\x03 \x01(\x0b\x32\x1f.cm.proto.ProcessingUnitContextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSINGUNITCONTEXT']._serialized_start=30
  _globals['_PROCESSINGUNITCONTEXT']._serialized_end=247
  _globals['_FRAMEMSG']._serialized_start=249
  _globals['_FRAMEMSG']._serialized_end=339
# @@protoc_insertion_point(module_scope)
